const promociones = [
  {
    id: 1,
    empresa: "Abarrosaurios",
    urlImg: "img/abarrosaurios.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Calle Rosita alvirez 290 Benito Juárez 57000",
  },
  {
    id: 2,
    empresa: "Cafeteria Sociedad Crepas",
    urlImg: "img/sociedadCrepas.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Av. Gustavo Baz 173 Benito Juárez 57000",
  },
  {
    id: 3,
    empresa: "Cremería La Reina de Neza",
    urlImg: "img/reinaNeza.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Av. Gustavo Baz 224 Benito Juárez 57000",
  },
  {
    id: 4,
    empresa: "Cremería y Abarrotes Regina",
    urlImg: "img/abaRegina.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Calle Mariquita linda 297 Benito Juárez 57000",
  },
  {
    id: 5,
    empresa: "Dental fresh",
    urlImg: "img/dentalFresh.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Calle Mariquita linda 292 Benito Juárez 57000",
  },
  {
    id: 6,
    empresa: "Distribuidora Electrica LUGO",
    urlImg: "img/lugo.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Av. Carmelo Pérez 625 Benito Juárez 57000",
  },
  {
    id: 7,
    empresa: "El Carretón de Sinaloa",
    urlImg: "img/sinaloa.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "4ta Avenida 244 Benito Juárez 57000",
  },
  {
    id: 8,
    empresa: "El Taco Perrón",
    urlImg: "img/perron.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Av. Carmelo Pérez 677 Benito Juárez 57000",
  },
  {
    id: 9,
    empresa: "Fiesta shopp",
    urlImg: "img/fiestaShop.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "4ta Avenida 231 Benito Juárez 57000",
  },
  {
    id: 10,
    empresa: "Huaraches Lupita",
    urlImg: "img/lupita.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Av. Gustavo Baz 297 Benito Juárez 57000",
  },
  {
    id: 11,
    empresa: "Lady Barber",
    urlImg: "img/ladyBarber.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Av. Rancho Grande 223 Benito Juárez 57000 ",
  },
  {
    id: 12,
    empresa: "Mamá Cocina",
    urlImg: "img/mamaCocina.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "4ta Avenida 193 Benito Juárez 57000",
  },
  {
    id: 13,
    empresa: "Papelería ANA",
    urlImg: "img/papeleriaAna.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Calle Mariquita linda 268 Benito Juárez 57000",
  },
  {
    id: 14,
    empresa: "Papelería HA",
    urlImg: "img/papeleriaHA.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Mariquita Linda 189 Benito Juárez 57000",
  },
  {
    id: 15,
    empresa: "Papelería impresion digital SAYA",
    urlImg: "img/saya.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    direccion: "Calle Mariquita linda 290 Benito Juárez 57000",
  },
];
