const promociones = [
  {
    id: 1,
    empresa: "Papelería Gaby",
    urlImg: "img/tienda1.png",
    calificacion: "4.8",
    highLight: "25% o cashback",
    distancia: "Papelería - 150m",
    direccion: "Dirección ficticia #123,CP 12345",
  },
  {
    id: 2,
    empresa: "Miscelanea La Cabaña",
    urlImg: "img/tienda2.png",
    calificacion: "4.8",
    highLight: "25% o cashback",
    distancia: "Papelería - 150m",
    direccion: "Dirección ficticia #123,CP 12345",
  },
  {
    id: 3,
    empresa: "Taqueria El Sol",
    urlImg: "img/tienda3.png",
    calificacion: "4.8",
    highLight: "25% o cashback",
    distancia: "Papelería - 150m",
    direccion: "Dirección ficticia #123,CP 12345",
  },
  {
    id: 4,
    empresa: "Miscelanea La Pasadita",
    urlImg: "img/tienda4.png",
    calificacion: "4.8",
    highLight: "25% o cashback",
    distancia: "Papelería - 150m",
    direccion: "Dirección ficticia #123,CP 12345",
  },
  {
    id: 5,
    empresa: "Papeleria El Pecas",
    urlImg: "img/tienda5.jpg",
    calificacion: "4.8",
    highLight: "25% o cashback",
    distancia: "Papelería - 150m",
    direccion: "Dirección ficticia #123,CP 12345",
  },
];
