const detalle = [
  {
    id: 1,
    empresa: "Abarrosaurios",
    urlImg: "img/abarrosaurios.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion:
      "Calle Rosita Alvírez 290, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5624385283,
    descripcion:
      "VENTA DE ARTICULOS ABARROTES COMO LECHES, EMBUTIDOS, REFRESCOS, ENLATADOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 2,
    empresa: "Abarrotera Richilli",
    urlImg: "img/richili.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Organillero 95, Benito juuarez",
    telefono: 5537233705,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 3,
    empresa: "Abarrotes Calderon ",
    urlImg: "img/calderon.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Calle Rancho Grande 215 Benito Juarez 5700",
    telefono: 5523270697,
    descripcion:
      "VENTA DE ABARROTES, REFRESCOS, BOTANAS, SUAVIZANTES, SEMILLAS Y ALIMENTO DE MASCOTAS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 4,
    empresa: "Abarrotes El Fenix",
    urlImg: "img/fenix.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion:
      "Calle Mariquita Linda 292, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5510128980,
    descripcion:
      "ESTABLECIMEINTO DEDICADO A LA VENTA DE ABARROTES TALES COMO, HUEVO, AZUCAR, GALLETAS DULCES, REFRESCOS, BOTANAS, SOPAS, LECHE, PAPEL DE BAÑO, SUAVISANTES ETC.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 5,
    empresa: "Abarrotes el Zaguancito",
    urlImg: "img/zaguancito.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Mariquita 104, vol Benito Juárez, 57000",
    telefono: 5545565552,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 6,
    empresa: "Abarrotes Juanita",
    urlImg: "img/juanita.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Perjura 99 Benito Juárez 57000",
    telefono: null,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 7,
    empresa: "Abarrotes la Juquilita",
    urlImg: "img/juquilita.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "San Marqueña 106 Benito Juárez, 57000",
    telefono: 7224597992,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 8,
    empresa: "Abarrotes Lyly",
    urlImg: "img/lili.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Mariquita Linda 39 Benito Juárez 57000",
    telefono: 5617189425,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 9,
    empresa: "Abarrotes Owen",
    urlImg: "img/owen.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Las mixtecas 268, Benito Juárez 57000",
    telefono: 5513201708,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 10,
    empresa: "Abarrotes Perla",
    urlImg: "img/perla.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion:
      "Calle Mañanitas 215, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5534208569,
    descripcion:
      "COMERCIO DEDICADO A LA VENTA DE LACTEOS, EMBUTIDOS, DULCES, REFRESCOS, BOTANAS, COMIDA PARA PERRO Y GATO , MAIZ POZOLERO, CIGARROS, CEREALES Y BEBIDAS ENERGETIZANTES.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 11,
    empresa: "Abarrotes Todito ",
    urlImg: "img/todito.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Calle Perjura 2 Benito Juárez 57000",
    telefono: 5531230839,
    descripcion:
      "VENTA DE ABARROTES COMO BOTANAS REFRESCOS, GALLETAS, ENLATADOS, SUEROS AGUA EMBOTELLADA Y PAPEL ALUMINIO , SUAVIZANTE DE TELAS Y CLORO.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 12,
    empresa: "Abarrotes y Semillas Lupita",
    urlImg: "img/semillaslupita.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion: "Calle Cariño 370 Benito Juárez 57000",
    telefono: 5563997584,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 13,
    empresa: "Agencia de viajes HEROCHE",
    urlImg: "img/herochy.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Viajes",
    direccion: "Av Carmelo Pérez 843 col Benito Juárez 57000",
    telefono: 5546928564,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 14,
    empresa: "Auto Cerrajeria Judith",
    urlImg: "img/judith.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Servicio",
    direccion: "Carmelo Perez 749 Benito Juárez 57000",
    telefono: 5576169133,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 15,
    empresa: "Cafeteria Sociedad Crepas",
    urlImg: "img/sociedad.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Av. Gustavo Baz 173, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5585677166,
    descripcion:
      "VENTA  DE CREPAS, PAPAS A LA FRANCESA, CAFÉ, FRAPPES, Y CAPUCHINOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 16,
    empresa: "Cocina Economica Mary",
    urlImg: "img/mary.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Av. 4a. Avenida 160, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: null,
    descripcion:
      "COMERCIO DEDICADO A LA VENTA Y CONSUMO DE ALIMENTOS Y COMIDA CASERA, POZOLE, AGUA, REFRESCOS, QUESADILLAS Y CHILAQUILES . LA ESENCIA DEL LOCAL ES LA COMIDA CORRIDA .",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 17,
    empresa: "Comida Don Adrian",
    urlImg: "img/adrian.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion: "Calle Cecilia 4 Benito Juarez 57000 ",
    telefono: 5584777810,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 18,
    empresa: "Cremería La Güera",
    urlImg: "img/cremeriawera.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Cremería",
    direccion: "Av Carmelo Pérez 840 Benito Juárez 57000",
    telefono: 5520932356,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 19,
    empresa: "Cremería La Reina de Neza",
    urlImg: "img/reina.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion:
      "Av. Gustavo Baz 224, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5522640696,
    descripcion:
      "VENTA DE REFRESCO, BEBIDAS, BOTANAS, EMBUTIDOS, LACTEOS Y DERIVADOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 20,
    empresa: "Cremería y Abarrotes Regina",
    urlImg: "img/regina.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion:
      "Calle Mariquita Linda 297, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: null,
    descripcion:
      "VENTA DE ABARROTES, ENLATADOS, REFRESCOS, EMBUTIDOS , LACTEOS Y DERIVADOS, ",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 21,
    empresa: "Dental fresh",
    urlImg: "img/dentalFresh.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Dentista",
    direccion:
      "Calle Mariquita Linda 292, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5971143962,
    descripcion:
      "NEGOCIO DEDICADO AL CUIDADO DENTAL, EXTRACCIONES, ENDODONCIAS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 22,
    empresa: "Didacti risas",
    urlImg: "img/didactirisas.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Jugueteria",
    direccion: "Av Chimalhuacán 451, Benito Juárez 57000",
    telefono: 5545454111,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 23,
    empresa: "Distribuidora Electrica LUGO",
    urlImg: "img/lugo.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Tlapaleria",
    direccion:
      "Av. Carmelo Pérez 625, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5574495548,
    descripcion:
      "VENTA DE  ELECTRICOS, ELECTRONICOS Y MATERIAL PARA INSTALACIONES ELECTRICAS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 24,
    empresa: "Dulceria y Materias Primas Karen",
    urlImg: "img/karen.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Dulceria",
    direccion:
      "Av. Chimalhuacán 474, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5530538913,
    descripcion:
      "DIRIGIDO A ESCUELAS, FIESTAS VENTA DE DULCES, PALETAS, PIÑATAS, BOTANAS, BEBIDAS COMO AGUA, FRUTSI Y BOING. EL FUERTE ES LA BOTANA Y EL DULCE",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 25,
    empresa: "El Carretón de Sinaloa",
    urlImg: "img/sinaloa.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Av. 4a. Avenida 244, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5521973978,
    descripcion:
      "OFRECE TACOS DE CORTES DE RES, CERDO Y EMBUTIDOS INTERNACIONALES",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 26,
    empresa: "El Taco Perrón",
    urlImg: "img/perron.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Av. Carmelo Pérez 677, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5610923555,
    descripcion: " DESAYUNOS, COMIDA CORRIDA, AGUAS DE SABOR, Y LICUADOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 27,
    empresa: "Farmacia Genéricos",
    urlImg: "img/genericos.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Farmacia",
    direccion: "Cama de Piedra 51 Benito Juárez, 57000",
    telefono: 5511898282,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 28,
    empresa: "Farmacia Tauro 2",
    urlImg: "img/tauro.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Farmacia",
    direccion:
      "Av. 4a. Avenida 159, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5528860686,
    descripcion:
      "COMERCIO DESTINADO A LA VENTA DE PRODUCTOS DE MEDICAMENTOS TALES COMO ANTIBIOTICOS, SUEROS, PAÑALES, GEL, TOALLAS FEMENINAS, MEDICAMENTO GENERICO Y PRODUCTOS NATURISTAS RECARGAS Y PAGO DE SERVICIOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 29,
    empresa: "Fel & Ever Productos de Belleza",
    urlImg: "img/felever.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Belleza",
    direccion:
      "Av. Gustavo Baz 190, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5614946101,
    descripcion:
      "VENTA DE TRATAMIENTOS CAPILARES COMO CREMAS, SHAMPOO, TINTES. VENDIENDO TAMBIEN CEPILLOS, PEINES, ALICATES, PINZAS DEPILADORAS, PESTAÑAS POSTIZAS, EXTENSIONES PARA CABELLO, UÑAS Y MATERIAL PARA UÑAS DE ACRILICO",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 30,
    empresa: "Fiesta shopp",
    urlImg: "img/fiestaShop.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Salón de fiestas",
    direccion:
      "Av. 4a. Avenida 231, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5535155808,
    descripcion: "VENTA DE ARTICULOS PARA FIESTAS, PIÑATAS , GLOBOS Y ADORNOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 31,
    empresa: "Huaraches Lupita",
    urlImg: "img/lupita.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Av. Gustavo Baz 297, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5514817520,
    descripcion:
      "OFRECE ANTOJITOS MEXICANOS COMO HUARACHES, PAMBAZOS, QUESADILLAS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 32,
    empresa: "Infantiles Villada",
    urlImg: "img/villada.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Jugueteria",
    direccion: "Av. Vicente Villada 727 Benito Juárez 57000",
    telefono: 5511381183,
    descripcion:
      "LOCAL DEDICADO AL COMERCIO DE JUGUETES PARA NIÑOS Y NIÑAS COMO MONTABLES, MUÑECA, JUEGOS DIDACTICOS, CARRITOS DE CONTROL REMOTO, PATINETAS, AVALANCHAS, ASI MISMO CUENTA CON CARRIOLAS, ANDADERAS, SILLAS INFANTILES, MUEBLES PARA RECAMARA COMO BURÓ Y CAMITAS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 33,
    empresa: "Internet La Madrugada ",
    urlImg: "img/madrugada.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Papelería",
    direccion: "Av. Gustavo Baz 196 Benito Juárez 57000",
    telefono: 5544759442,
    descripcion:
      "ESTE NEGOCIO ESTA DEDICADO A PRESENTAR SERVICIO DE COMPUTADORAS INTERNET, COPIAS, VENTA DE PAPELERIA, PLUMAS , LAPIZ, JUEGOS GEOMETRICOS, JUGUETES, PLUMONES, REGALOS, REALIZA ESCANER DE DOCUMENTOS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 34,
    empresa: "Lady Barber",
    urlImg: "img/ladyBarber.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Belleza",
    direccion:
      "Av. Rancho Grande 223, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: null,
    descripcion:
      " ESTETICA. CORTES DE PELO PARA DAMAS Y CABALLEROS, TINTES Y ARREGLO DE UÑAS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 35,
    empresa: "Lipstick studio",
    urlImg: "img/lipstick.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Belleza",
    direccion: "Cascabel 96 col Benito Juárez",
    telefono: null,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 36,
    empresa: "Los Mezcalitos",
    urlImg: "img/mezcalitos.png",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion: "Av. Gustavo Baz 205, Benito Juárez, 57000, Nezahualcóyotl",
    telefono: null,
    descripcion:
      "ESTE NEGOCIO ESTA DEDICADO A PRESENTAR SERVICIO DE COMPUTADORAS INTERNET, COPIAS, VENTA DE PAPELERIA, PLUMAS , LAPIZ, JUEGOS GEOMETRICOS, JUGUETES, PLUMONES, REGALOS, REALIZA ESCANER DE DOCUMENTOS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 37,
    empresa: "Mamá cocina",
    urlImg: "img/mamaCocina.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Av. 4a. Avenida 193, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5627338516,
    descripcion: "DESAYUNOS, Y COMIDA CORRIDA ",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 38,
    empresa: "Muebleria Pepes",
    urlImg: "img/pepes.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Muebleria",
    direccion:
      "Av. Gustavo Baz 161, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: null,
    descripcion:
      "VENTA DE MUEBLES, COMO SILLONES, CAMAS,ROPEROS, CABECERAS PARA EL HOGAR ",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 39,
    empresa: "NovaFast",
    urlImg: "img/novafast.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Abarrotes",
    direccion:
      "Calle Adelita 262, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5613827331,
    descripcion:
      "TIENDITA, CON VENTA DE REFRESCOS,  BOTANAS, ACEITES, CAFE DE SOBRE, CEREAL EN CAJA , IMPRESIONES, COPIAS , DOCUMENTOS PAGOS DE SERVICIO Y RECARGAS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 40,
    empresa: "Papelería ANA",
    urlImg: "img/ana.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Papelería",
    direccion:
      "Calle Mariquita Linda 268, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5539632032,
    descripcion: "VENTA DE ARTICULOS DE PAPELERIA EN GENERAL",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 41,
    empresa: "Papelería HA",
    urlImg: "img/ha.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Papelería",
    direccion:
      "Calle Mariquita Linda 189, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: null,
    descripcion: " IMPRESIONES, COPIAS Y VENTAS DE MATERIAL PARA OFICINA ",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 42,
    empresa: "Papelería impresion digital SAYA",
    urlImg: "img/saya.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Papelería",
    direccion:
      "Calle Mariquita Linda 290, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5579463463,
    descripcion:
      "VENTA DE ARTICULOS DE PAPELERIA E IMPRESION DE TODO TIPO DE DOCUMENTOS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 43,
    empresa: "Papeleria Osmara",
    urlImg: "img/osmara.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Papelería",
    direccion: "Av Chimalhuacán 485 Benito Juárez 57000",
    telefono: 5539950796
    ,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 44,
    empresa: "Papelería Victoria",
    urlImg: "img/victoria.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Papelería",
    direccion: "Escondida, 297 Benito Juárez 57000",
    telefono: 5618271416,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 45,
    empresa: "Pollería Yessi",
    urlImg: "img/yessi.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Polleria",
    direccion: "Calle Pagaré 2, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5573614901,
    descripcion:
      "VENTA UNICAMENTE DE POLLO FRESCO COMO PECHIGA, PIERNA Y MUSLO, SURTIDA. POLLO PARA FREIR TIPO KENTUCKY",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 46,
    empresa: "Publineza ",
    urlImg: "img/publineza.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Impresion",
    direccion: "Av Chimalhuacán 601 BENITO JUAREZ 57000 ",
    telefono: null,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 47,
    empresa: "Red velvet spa",
    urlImg: "img/velvet.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Belleza",
    direccion: "Cama de piedra 232, entre calle ardilla y cecilia",
    telefono: 5545687151,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 48,
    empresa: "Reparaciones de Pantallas ",
    urlImg: "img/servicioEsp.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Tecnología",
    direccion: "Calle Mixtecas 397 Colonia Benito Juárez 57000",
    telefono: 5559442697,
    descripcion:
      "REALIZAN INSTALACIONES Y REPARACIONES ELECTRICAS Y DE APARATOS ELÉCTRICOS.  ",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 49,
    empresa: "Sala De Uñas Coquette Nails",
    urlImg: "img/coquette.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Belleza",
    direccion: "Av Chimalhuacan 567 Benito Juarez 57000 ",
    telefono: 5620726665,
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 50,
    empresa: "Tacos El Zurdo",
    urlImg: "img/zurdo.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Calle Panchita 398, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5513903763,
    descripcion:
      "TACOS DE CECINA,CAMPECHANOS, LONGANIZA, CARNE ENCHILADA, SE VENDE POR TACO Y POR KILO. SERVICIO A DOMICILIO Y EVENTOS.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 51,
    empresa: "Tienda Naturista",
    urlImg: "img/naturista.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Salud",
    direccion:
      "Calle Panchita 393, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: null,
    descripcion:
      "EL COMERCIO SE DEDICA A LA VENTA DE PRODUCTOS NATURISTAS PARA EL CRECIMIENTO DE CABELLO, SUPLEMENTOS ALIMENTICIOS, VITAMINAS, REDUCTORES DE GRASA. ASÍ MISMO DAN CONSULTA Y TERAPIA PSICOLOGÍCA, MASAJES RELAJANTES Y CORRECTIVOS DE COLUMNAS",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 52,
    empresa: "Tortas y Chilaquiles Isabel",
    urlImg: "img/isabel.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion:
      "Calle Isabeles 196, Benito Juárez, 57000, Nezahualcóyotl, México",
    telefono: 5620544421,
    descripcion:
      "LOCAL PARA EL CONSUMO INTERNO Y PARA LLEVAR GRINGAS,HAMBURGUESAS, TACOS, CHILAQUILES, REFRESCOS, BOING, AGUA DE FRUTAS , JUGOS DE NARANJA. LA VENTA FUERTE SON LOS PAMBAZOS Y CHILAQUILES.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
  {
    id: 53,
    empresa: "Tortilleria Brabante",
    urlImg: "img/brabante.jpg",
    calificacion: 4.8,
    highlight: "25% o cashback",
    giro: "Comida",
    direccion: "Calandría  244 Benito Juarez  57000",
    telefono: 5523072961,
    descripcion:
      "TORTILLERIA VENTA DE SALSAS, TOTOPOS, MASA A GRANEL TORTILLAS, ARROZ, CHICHARRON.",
    compra: [
      { id: "1", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "2", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "3", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "4", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "5", dato: "Pago mayor a $35", gana: "Gana $10" },
      { id: "10", dato: "Pago mayor a $35", gana: "Gana $20" },
      { id: "15", dato: "Pago mayor a $35", gana: "Gana $30" },
      { id: "20", dato: "Pago mayor a $35", gana: "Gana $40" },
    ],
    reembolso: "$150",
    comoAplica: "Para hacer válida esta promo asegúrate de pagar con baz",
    TyC: 'Consulta TyC de la promoción "Paga con baz y gana más" en ',
    enlace: "baz.app",
    vigencia: "08/07/2022",
  },
];

const verDetalle = (element) => {
  const { compra } = element;
  let date = new Date(element.vigencia);
  let fecha =
    ("0" + date.getDate()).slice(-2) +
    "/" +
    ("0" + (date.getMonth() + 1)).slice(-2) +
    "/" +
    date.getFullYear();
  // console.log(date)
  let container = document.querySelector(".container");

  container.innerHTML += `
        <div class="container-promo">
            <img src=${element.urlImg} alt=${element.empresa} class="img-negocio">
            <div class="container-empresa">
              <p class="empresa">${element.empresa}</p>
              <div class="promo">
                <p class="calif">${element.calificacion} </p>
                <label >
                  <img src=\"img/score_on.png\" class="star"/>
                </label>
                <label>
                  <span class="separacion"> | </span>
                </label>
                <label>
                <img src=\"img/discount_off.png\" class="discount_off" />
                </label>
                <label class="discount_text">Gana hasta $150</label>
                </div>
                <label>
                  <span class="giro">${element.giro}</span>
                </label>
              
            </div>
        </div>
        
        <hr/>

        <div class="container-location">
            <img src=\"img/location_off.png\" class="location_off" />
            <p class="location">${element.direccion}</p>
        </div>
        
        <hr/>
        `;

  if (element.telefono === null) {
    container.innerHTML += `
              <div class="container-phone">
                
              </div>
            `;
  } else {
    container.innerHTML += `
              <div class="container-phone">
                <img src=\"img/mobile_off.png\" class="mobile_off" />
                <p class="mobile">${element.telefono}</p>
                <a href="tel:${element.telefono}" class="mobile-call">Llamar</a>
              </div>
            `;
  }

  container.innerHTML += `
        <hr/>

        <div class="container-reembolso">
        <p class="title-reembolso">Conoce cuánto puedes ganar.</p>
        </div>
        `;

  compra.forEach((e) => {
    container.innerHTML += `        
                <div class="container-reembolsos">
                    <span class="circulo">${e.id}</span>
                    <span class="dato">${e.dato} -</span>
                    <span class="gana">${e.gana}</span>
                </div>
                `;
  });

  container.innerHTML += `
  
          <div class="card-reembolso">
            <label class="num"> ${element.reembolso} <span class="total">Total a ganar</span></label>
            <div class="promo-valida">
              <img src=\"img/warning_on.png\" class="img_warning" />
              <label class="texto">${element.comoAplica}</label>
            </div>
            <p class="tyc">${element.TyC} 
              <a class="link" href="https://www.baz.app" >${element.enlace}</a> 
            </p>
            <div class="vigencia">
              <img src=\"img/calendar_off.png\" class="calendar_off" />
              <span class="fecha">Válida hasta ${fecha}</span>
            </div>
          </div>`;
};

let nombre = Number(location.search.substring(4));
let variable = detalle[nombre - 1];

verDetalle(variable);
